### ISSUE TITLE
Intune - Microsoft store app (new) - This app is not supposed in preview

### ISSUE THREAD

**Issue by zsmbrvr** [Weatherlights/Winget-AutoUpdate-Intune#4] opened 2023-01-30 17:17 UTC
I'm trying to deploy this with Intune as a store app, but once I select the app, website gives an error that the app is not supported in preview.
Am I doing something wrong?

**Comment by Weatherlights** [comment] 2023-01-30 23:42
Nope... sadly the Microsoft Store app (new) is in preview and Microsoft has not provided much information what makes an app a "not supported in preview" candidate.

So an update might resulted in that stuff. However I am investigating the issue and try to analyze why Microsoft started blocking the app during the preview and hope I can mitigate this :).

**Comment by zsmbrvr** [comment] 2023-01-31 08:12
Did you consider making a Windows app (Win32) instead of the LoB one?

**Comment by Weatherlights** [comment] 2023-01-31 09:07
That is not exactly how the Microsoft Store works :) Within the Microsoft store everything is treated as Win32 so there is no LoB app type. It is something within the installer itself that changed from version 1.02.0003 to 1.03.0003 that hit the preview limitation.

But I am already on it and experimenting on my Beta branch... sadly it takes a little time since Microsoft has to approve everything I do there. However you can deploy the app as Win32 or LoB using Intune if you do not want to wait :).

**Comment by hotzenwalder** [comment] 2023-01-31 09:09
It's a Win32 app in the new Microsoft store and Win32 apps are not supported in the preview. If it is a UWP app it would be supported at this time as far as I understand the new store
![2023-01-31 10_07_14-Search the Microsoft Store app (new) - Microsoft Endpoint Manager admin center e](https://user-images.githubusercontent.com/78266646/215716548-2ce4ca66-00d6-4573-b206-d34a85d998d9.png)


![2023-01-31 10_09_33-Add App - Microsoft Endpoint Manager admin center en nog 4 andere pagina's - Beh](https://user-images.githubusercontent.com/78266646/215717043-3cc1dcb8-fa04-44a4-84a3-4a7fee50faa6.png)

**Comment by Weatherlights** [comment] 2023-01-31 09:15
Hey @hotzenwalder that is not totally correct: Some Win32 apps are supported and also Winget-AutoUpdate-Configurator was supported in earlier versions. There is a intransparent rule that currently distinct what Win32 app is supported and what not.

For example: Adobe Acrobat Reader is currently supported as Win32 app and also my PolicyApplicator app is supported but Visual Studio Code is not :). Sorry for the confusion but Microsoft is not giving much information out at the moment :).

**Comment by hotzenwalder** [comment] 2023-01-31 09:16
I stand corrected. I was under the impression that every Win32 app was not supported. Hope they get it fixed for you a.s.a.p.

**Comment by Weatherlights** [comment] 2023-03-11 16:33
What mechanism are you using.

- If you use LoB: Just upload the new MSI into the old deployment.
- If you use Win32 app you can either replace the old app or create a new one with a supersedence relationship.
- If you used the new Store mechanism: Microsoft plans to support automatic update here but the mechanism is not working yet in the preview. Most promising way here: Use Uninstall to remove existing installations and then reassign the app...

**Comment by msellar-inst** [comment] 2023-03-17 21:01
Just chiming in as I was going to raise the same issue - I hope you get it sorted! it will be amazing!

You've prob already seen this:

After selecting a Win32 app from the search results, you may see a banner that states “This app is not supported in preview,” and you’re unable to proceed. There are some Win32 apps that either we don’t have enough information on or that have unreliable detection, installation, or upgradability and are, therefore, filtered out as they may not successfully be managed._

From <https://techcommunity.microsoft.com/t5/intune-customer-success/troubleshooting-the-microsoft-store-and-microsoft-intune/ba-p/3750341

**Comment by Weatherlights** [comment] 2023-03-18 19:05
That was a very usefull link. So the problem is probably that my installer ends up with having two entries into add/remove programs. This also explains that the app became unavailable as soon as I installed WAU during the intial installation (and not during the first policy synchronisation).

I will not try some mechanisms to hide the entry of WAU within the add/remove programs page.... let's see which one will please Microsoft :).

**Comment by fdoSkyeTec** [comment] 2023-04-12 10:10
Have there been some progress on this issue? I have the latest win32 version that works fine, but the auto update feature with Store (new) app would be great

**Comment by Weatherlights** [comment] 2023-04-12 10:18
Hey

currently I am still figuring out what will please Microsoft :) (As stupid as this sounds there is no real "direct contact" to microsoft so it is some sort of try and error). At the moment there is an update in certification that has a delay before WAU is installed (so instead of the setup installing WAU it is installed during the first synchronisation of policies).

I have created an "beta" store app with that behaviour that was not blocked from the preview so there is a good chance that this will work.

If you want to test this beta app too (where the store update works) you can find it by searching for XP8M0M5N8RB8W7 in the new store app wizard. I will use this "beta" app also later for testing before I put stuff in the main release.

Best
Hauke

**Comment by fdoSkyeTec** [comment] 2023-04-12 10:24
> Hey
> 
> currently I am still figuring out what will please Microsoft :) (As stupid as this sounds there is no real "direct contact" to microsoft so it is some sort of try and error). At the moment there is an update in certification that has a delay before WAU is installed (so instead of the setup installing WAU it is installed during the first synchronisation of policies).
> 
> I have created an "beta" store app with that behaviour that was not blocked from the preview so there is a good chance that this will work.
> 
> If you want to test this beta app too (where the store update works) you can find it by searching for XP8M0M5N8RB8W7 in the new store app wizard. I will use this "beta" app also later for testing before I put stuff in the main release.
> 
> Best Hauke

Yeah, I don't doubt in. The new store is really hit and miss on what works and on what is incompatable. Adobe Reader have had the same issues for what feels like forever, worked today suddenly.

Awesome! I will give it a try. Works for a smb where I can try on some test machines. Much appreciated :)

**Comment by Weatherlights** [comment] 2023-04-13 05:26
It worked the app is available in Intune again and will not automatically update :). I will post a release during the day.

**Closed by Weatherlights** 2023-04-13 05:26 UTC

**Comment by zsmbrvr** [comment] 2023-04-13 05:28
If it doesn't update automatically, then how do you update it?

**Comment by Weatherlights** [comment] 2023-04-13 07:18
The update was just certified :) Have a little patience and if it does not update until tomorrow give me a short notice.

**Comment by fdoSkyeTec** [comment] 2023-04-13 07:25
Seems good on my end. The preview one you sendt and this new one installs 1.04.0008
Weirdly the policy in Intune just says pending, but on my machine it seems to have the same triggers set in the Policy
